// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDXbEoQWDewSwfJin0cYOmsIgpLzhgPcQ',
    appId: '1:456501816149:web:44f19b21b603c8002c9ddc',
    messagingSenderId: '456501816149',
    projectId: 'ebbinghaus-app-e11c1',
    authDomain: 'ebbinghaus-app-e11c1.firebaseapp.com',
    databaseURL: 'https://ebbinghaus-app-e11c1.firebaseio.com',
    storageBucket: 'ebbinghaus-app-e11c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxJecQ8nieLoTSrpgDZed8ofI4l0iNa3o',
    appId: '1:456501816149:android:d65ac3da7c00cf7b2c9ddc',
    messagingSenderId: '456501816149',
    projectId: 'ebbinghaus-app-e11c1',
    databaseURL: 'https://ebbinghaus-app-e11c1.firebaseio.com',
    storageBucket: 'ebbinghaus-app-e11c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoNuorGnOHPfdLvhTXQs1fLTrLQcEbCXk',
    appId: '1:456501816149:ios:76401448eed464172c9ddc',
    messagingSenderId: '456501816149',
    projectId: 'ebbinghaus-app-e11c1',
    databaseURL: 'https://ebbinghaus-app-e11c1.firebaseio.com',
    storageBucket: 'ebbinghaus-app-e11c1.appspot.com',
    iosClientId: '456501816149-foto8khptlmguem624r6mtbd8clhehdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.remindr',
  );
}
